name: know_karelia
description: "A new Flutter project."
# Запрещает публикацию пакета на pub.dev.
publish_to: 'none'

# Определяет версию и номер сборки приложения.
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

# Зависимости, необходимые для работы вашего пакета.
dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.0.1
  path: ^1.8.3
  sqflite: ^2.3.0
  yaml: any
  font_awesome_flutter:
  # Добавляет шрифт иконок Cupertino для приложений iOS.
  sqflite_common_ffi:
  path_provider_aurora:
    git:
      url: https://gitlab.com/omprussia/flutter/flutter-plugins.git
      ref: path_provider_aurora-0.5.0
      path: packages/path_provider/path_provider_aurora
  sqflite_aurora:
    git:
      url: https://gitlab.com/omprussia/flutter/flutter-plugins.git
      ref: sqflite_aurora-0.5.0
      path: packages/sqflite/sqflite_aurora
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0

# Настройка иконок запуска приложения.
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon_round.png"
  min_sdk_android: 21

flutter:
  # Включает шрифт Material Icons для использования иконок.
  uses-material-design: true

  # Добавление ассетов в приложение.
  assets:
    - db/images/easy/
    - db/images/hard/
    - db/images/medium/
    - db/know_karelia.db
    - db/guide/
    - db/avatars/
    - assets/
    - assets/fonts/
    - assets/icon/

  # Добавление пользовательских шрифтов.
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700
        - asset: assets/fonts/Ubuntu-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Ubuntu-Italic.ttf
          style: italic
        - asset: assets/fonts/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Ubuntu-Regular.ttf
